In [53]:
import pandas as pd

In [54]:
df_en = pd.read_csv("/Users/kaankorkmaz/projects_KK/thesis/icd_codes_en.csv", index_col=0)
df_de = pd.read_csv("/Users/kaankorkmaz/projects_KK/thesis/icd_codes_de.csv", index_col=0)

In [55]:
df_en.head(20)

   icd_code                                      icd_code_desc
0      A000  Cholera due to Vibrio cholerae 01, biovar chol...
1      A001    Cholera due to Vibrio cholerae 01, biovar eltor
2      A009                               Cholera, unspecified
3     A0100                         Typhoid fever, unspecified
4     A0101                                 Typhoid meningitis
5     A0102               Typhoid fever with heart involvement
6     A0103                                  Typhoid pneumonia
7     A0104                                  Typhoid arthritis
8     A0105                              Typhoid osteomyelitis
9     A0109             Typhoid fever with other complications
10     A011                                Paratyphoid fever A
11     A012                                Paratyphoid fever B
12     A013                                Paratyphoid fever C
13     A014                     Paratyphoid fever, unspecified
14     A020                               Salmonella enteritis
15     A021                                  Salmonella sepsis
16    A0220        Localized salmonella infection, unspecified
17    A0221                              Salmonella meningitis
18    A0222                               Salmonella pneumonia
19    A0223                               Salmonella arthritis

In [56]:
df_de.head()

  icd_code                                   icd_code_desc_de
0      A00                                            Cholera
1     A000  Cholera durch Vibrio cholerae O:1, Biovar chol...
2     A001    Cholera durch Vibrio cholerae O:1, Biovar eltor
3     A009                    Cholera, nicht näher bezeichnet
4      A01                  Typhus abdominalis und Paratyphus

In [57]:
df_en.shape

(72621, 2)

In [58]:
df_de.shape

(16203, 2)

In [75]:
df_combined = pd.merge(df_en, df_de, how="outer", on="icd_code")
df_combined.head(25)

,icd_code,icd_code_desc,icd_code_desc_de
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...","Cholera durch Vibrio cholerae O:1, Biovar chol..."
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor","Cholera durch Vibrio cholerae O:1, Biovar eltor"
2,A009,"Cholera, unspecified","Cholera, nicht näher bezeichnet"
3,A0100,"Typhoid fever, unspecified",NaN
4,A0101,Typhoid meningitis,NaN
5,A0102,Typhoid fever with heart involvement,NaN
6,A0103,Typhoid pneumonia,NaN
7,A0104,Typhoid arthritis,NaN
8,A0105,Typhoid osteomyelitis,NaN
9,A0109,Typhoid fever with other complications,NaN
10,A011,Paratyphoid fever A,Paratyphus A
11,A012,Paratyphoid fever B,Paratyphus B
12,A013,Paratyphoid fever C,Paratyphus C
13,A014,"Paratyphoid fever, unspecified","Paratyphus, nicht näher bezeichnet"
14,A020,Salmonella enteritis,Salmonellenenteritis
15,A021,Salmonella sepsis,Salmonellensepsis
16,A0220,"Localized salmonella infection, unspecified",NaN
17,A0221,Salmonella meningitis,NaN
18,A0222,Salmonella pneumonia,NaN
19,A0223,Salmonella arthritis,NaN
20,A0224,Salmonella osteomyelitis,NaN
21,A0225,Salmonella pyelonephritis,NaN
22,A0229,Salmonella with other localized infection,NaN
23,A028,Other specified salmonella infections,Sonstige näher bezeichnete Salmonelleninfektionen
24,A029,"Salmonella infection, unspecified","Salmonelleninfektion, nicht näher bezeichnet"

In [76]:
df_combined.shape

(81131, 3)

### Save the Combined Dataset

In [77]:
df_combined.to_csv('/Users/kaankorkmaz/projects_KK/thesis/icd_codes_combined.csv')

### Code Lookup

In [78]:
df_en.loc[(df_en.icd_code == "A011")]

   icd_code        icd_code_desc
10     A011  Paratyphoid fever A

### Matching rows

In [79]:
df_combined[(df_combined["icd_code_desc_de"].isna() == False)]

,icd_code,icd_code_desc,icd_code_desc_de
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...","Cholera durch Vibrio cholerae O:1, Biovar chol..."
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor","Cholera durch Vibrio cholerae O:1, Biovar eltor"
2,A009,"Cholera, unspecified","Cholera, nicht näher bezeichnet"
10,A011,Paratyphoid fever A,Paratyphus A
11,A012,Paratyphoid fever B,Paratyphus B
...,...,...,...
81126,U995,NaN,Nicht belegte Schlüsselnummer U99.5!
81127,U996,NaN,Nicht belegte Schlüsselnummer U99.6!
81128,U997,NaN,Nicht belegte Schlüsselnummer U99.7!
81129,U998,NaN,Nicht belegte Schlüsselnummer U99.8!
81130,U999,NaN,Nicht belegte Schlüsselnummer U99.9!

### Non-matching rows
If necessary, the missing descriptions from this list will be scraped additionally.

In [82]:
# English description is missing. 
df_english_missing = df_combined[(df_combined["icd_code_desc"].isna() == True)]

In [83]:
# German description is missing. 
df_german_missing = df_combined[(df_combined["icd_code_desc_de"].isna() == True)]

### Save non-matching rows to be used in additional scraping

In [85]:
df_english_missing.to_csv('/Users/kaankorkmaz/projects_KK/thesis/icd_codes_english_missing.csv')
df_german_missing.to_csv('/Users/kaankorkmaz/projects_KK/thesis/icd_codes_german_missing.csv')