# ICD Codes - German
Data source - 2021 ICD-10-GM <br>
https://www.dimdi.de/dynamic/de/klassifikationen/downloads/?dir=icd-10-gm

In [35]:
import pandas as pd

In [36]:
names = ["Klassifikationsebene", 
         "Ort_der_Schlüsselnummer_im_Klassifikationsbaum",
         "Art_der_Vier-undFünfsteller",
         "Kapitelnummer",
         "ersterDreistellerderGruppe",
         "SchlüsselnummerohneeventuellesKreuz",
         "SchlüsselnummerohneStrichSternundAusrufezeichen",
         "SchlüsselnummerohnePunktStrichSternundAusrufezeichen",
         "Klassentitel",
         "TiteldesdreistelligenKodes",
         "TiteldesvierstelligenKodes",
         "TiteldesfunfstelligenKodes",
         "VerwendungderSchlüsselnummer",
         "VerwendungderSchlüsselnummernachParagraph301"
         "BezugzurMortalitätsliste1",
         "BezugzurMortalitätsliste2",
         "BezugzurMortalitätsliste3",
         "BezugzurMortalitätsliste4",
         "BezugzurMortalitätsliste",
         "GeschlechtsbezugderSchlüsselnummer",
         "ArtdesFehlersbeiGeschlechtsbezug",
         "untereAltersgrenzefüreineSchlüsselnummer",
         "obereAltersgrenzefüreineSchlüsselnummer",
         "ArtdesFehlersbeiAltersbezug",
         "KrankheitinMitteleuropaSehrSelten?",
         "SchlüsselnummermitInhaltbelegt?",
         "IfSG-Meldung",
         "IfSG-Labor"         
        ]
col_names = ["code_description"]
df = pd.read_csv("/Users/kaankorkmaz/Downloads/icd10gm2021syst-meta-20201111/Klassifikationsdateien/icd10gm2021syst_kodes.txt",
                             sep=";", names=names, index_col=False)

In [37]:
df.head()

,Klassifikationsebene,Ort_der_Schlüsselnummer_im_Klassifikationsbaum,Art_der_Vier-undFünfsteller,Kapitelnummer,ersterDreistellerderGruppe,SchlüsselnummerohneeventuellesKreuz,SchlüsselnummerohneStrichSternundAusrufezeichen,SchlüsselnummerohnePunktStrichSternundAusrufezeichen,Klassentitel,TiteldesdreistelligenKodes,...,BezugzurMortalitätsliste,GeschlechtsbezugderSchlüsselnummer,ArtdesFehlersbeiGeschlechtsbezug,untereAltersgrenzefüreineSchlüsselnummer,obereAltersgrenzefüreineSchlüsselnummer,ArtdesFehlersbeiAltersbezug,KrankheitinMitteleuropaSehrSelten?,SchlüsselnummermitInhaltbelegt?,IfSG-Meldung,IfSG-Labor
0,3,N,X,1,A00,A00.-,A00,A00,Cholera,Cholera,...,4-002,001,9,9,9999,9999,9,J,J,J
1,4,T,X,1,A00,A00.0,A00.0,A000,"Cholera durch Vibrio cholerae O:1, Biovar chol...",Cholera,...,4-002,001,9,9,9999,9999,9,J,J,J
2,4,T,X,1,A00,A00.1,A00.1,A001,"Cholera durch Vibrio cholerae O:1, Biovar eltor",Cholera,...,4-002,001,9,9,9999,9999,9,J,J,J
3,4,T,X,1,A00,A00.9,A00.9,A009,"Cholera, nicht näher bezeichnet",Cholera,...,4-002,001,9,9,9999,9999,9,J,J,J
4,3,N,X,1,A00,A01.-,A01,A01,Typhus abdominalis und Paratyphus,Typhus abdominalis und Paratyphus,...,4-002,002,9,9,9999,9999,9,N,J,J

In [38]:
cols_to_keep = ["SchlüsselnummerohnePunktStrichSternundAusrufezeichen", "Klassentitel"]
df_final = df[cols_to_keep]

In [39]:
df_final.head(20)

,SchlüsselnummerohnePunktStrichSternundAusrufezeichen,Klassentitel
0,A00,Cholera
1,A000,"Cholera durch Vibrio cholerae O:1, Biovar chol..."
2,A001,"Cholera durch Vibrio cholerae O:1, Biovar eltor"
3,A009,"Cholera, nicht näher bezeichnet"
4,A01,Typhus abdominalis und Paratyphus
5,A010,Typhus abdominalis
6,A011,Paratyphus A
7,A012,Paratyphus B
8,A013,Paratyphus C
9,A014,"Paratyphus, nicht näher bezeichnet"
10,A02,Sonstige Salmonelleninfektionen
11,A020,Salmonellenenteritis
12,A021,Salmonellensepsis
13,A022,Lokalisierte Salmonelleninfektionen
14,A028,Sonstige näher bezeichnete Salmonelleninfektionen
15,A029,"Salmonelleninfektion, nicht näher bezeichnet"
16,A03,Shigellose [Bakterielle Ruhr]
17,A030,Shigellose durch Shigella dysenteriae
18,A031,Shigellose durch Shigella flexneri
19,A032,Shigellose durch Shigella boydii

### Rename columns

In [40]:
df_final = df_final.rename(columns={"SchlüsselnummerohnePunktStrichSternundAusrufezeichen": "icd_code",
                         "Klassentitel": "icd_code_desc_de"})

### Save data

In [41]:
df_final.to_csv('/Users/kaankorkmaz/projects_KK/thesis/icd_codes_de.csv')